const test=require('node:test');const assert=require('node:assert/strict');const express=require('express');const vm=require('node:vm');
const {createTrainingSecurity,bootstrap,TRAINING_PATHS}=require('../training-security');const {createTrainingToken}=require('../training-token');
const secret='synthetic-training-test-secret';
function token(id='staff-a',features=['practice','game'],locations=['gym-a']){return createTrainingToken({admin:{id,email:id+'@example.test',name:id,role:'manager'},features,locationIds:locations,secret}).token;}
async function fixture(fn,{reserve}={}){
 let paid=0;let reservations=0;let hold;
 const session={owner_id:'staff-a',training_feature:'practice',started_at:Date.now(),messages:[{role:'assistant',content:'hello'},{role:'user',content:'hi'},{role:'assistant',content:'yes'},{role:'user',content:'okay'}]};
 const guard=createTrainingSecurity({secret:()=>secret,getSession:id=>id==='session-a'?session:null,canonicalLocationId:x=>x,getPlayerById:async()=>({email:'staff-b@example.test'}),reserveUsage:async(...args)=>{reservations++;return reserve?reserve(...args):{allowed:true};}});
 const app=express();app.use(express.json());app.use(TRAINING_PATHS,guard.auth);
 app.get('/practice',(req,res)=>res.send('<html><head></head><body>practice</body></html>'));
 app.get('/airafitnessclosinggame',(req,res)=>res.send('<html><head></head><body>game</body></html>'));
 for(const [path,action] of [['start','start'],['turn','turn'],['end','end'],['voice/session','voice']])app.post('/practice/'+path,guard.action(action),(req,res)=>{paid++;if(req.body.hold){hold=()=>{if(!res.writableEnded)res.json({ok:true});};}else res.json({ok:true});});
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const request=(path,body,t=token(),headers={})=>fetch(base+path,{method:body?'POST':'GET',headers:{...(t?{Authorization:'Bearer '+t}:{}),'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});
 try{await fn({request,session,paid:()=>paid,reservations:()=>reservations,release:()=>hold?.()});}finally{hold?.();server.closeAllConnections();await new Promise(r=>server.close(r));}
}
test('all four anonymous paid routes denied before quota or provider',()=>fixture(async f=>{for(const p of ['start','turn','end','voice/session'])assert.equal((await f.request('/practice/'+p,{},null)).status,401);assert.equal(f.paid(),0);assert.equal(f.reservations(),0);}));
test('valid scoped staff launches a protected page, no-store, no-referrer',()=>fixture(async f=>{const r=await f.request('/practice');assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('referrer-policy'),'no-referrer');assert.match(await r.text(),/history.replaceState/);}));
test('missing feature denies both page and paid action',()=>fixture(async f=>{assert.equal((await f.request('/practice',null,token('staff-a',['game']))).status,403);assert.equal((await f.request('/practice/start',{},token('staff-a',['game']))).status,403);assert.equal((await f.request('/airafitnessclosinggame',null,token('staff-a',['practice']))).status,403);assert.equal(f.paid(),0);}));
test('session owner, expiry and gym scope enforced',()=>fixture(async f=>{assert.equal((await f.request('/practice/turn',{session_id:'session-a',message:'hi'},token('staff-b'))).status,404);assert.equal((await f.request('/practice/start',{location_id:'gym-b'})).status,403);assert.equal((await f.request('/practice/start',{mode:'game',player_id:'other'})).status,403);f.session.started_at=0;assert.equal((await f.request('/practice/end',{session_id:'session-a'})).status,404);assert.equal(f.paid(),0);}));
test('oversized and invalid messages rejected before reservations',()=>fixture(async f=>{for(const message of ['x'.repeat(2001),{},''])assert.equal((await f.request('/practice/turn',{session_id:'session-a',message})).status,400);assert.equal((await f.request('/practice/end',{session_id:'session-a',messages:[{role:'system',content:'bad'}]})).status,400);assert.equal(f.reservations(),0);}));
test('one scoring attempt prevents repeat charges and emails',()=>fixture(async f=>{assert.equal((await f.request('/practice/end',{session_id:'session-a'})).status,200);assert.equal((await f.request('/practice/end',{session_id:'session-a'})).status,409);assert.equal(f.paid(),1);}));
test('parallel requests for one identity blocked, even with another token/header',()=>fixture(async f=>{const first=f.request('/practice/turn',{session_id:'session-a',message:'hello',hold:true});while(!f.paid())await new Promise(r=>setTimeout(r,2));assert.equal((await f.request('/practice/turn',{session_id:'session-a',message:'again'},token(),{'X-Forwarded-For':'1.2.3.4'})).status,429);f.release();assert.equal((await first).status,200);assert.equal(f.paid(),1);}));
test('durable quota rejects before paid work',()=>fixture(async f=>{assert.equal((await f.request('/practice/start',{})).status,429);assert.equal(f.paid(),0);},{reserve:async()=>({allowed:false,status:429,error:'limit'})}));
test('quota outage fails closed',()=>fixture(async f=>{assert.equal((await f.request('/practice/start',{})).status,503);assert.equal(f.paid(),0);},{reserve:async()=>{throw new Error('offline');}}));
test('browser wrapper attaches credential only to this recorder training origin',async()=>{const calls=[];const listeners={};let cleaned;const location={href:'https://recorder.example/practice?training_token=secret&embed=1',origin:'https://recorder.example'};const context={URL,Headers,location,history:{replaceState:(a,b,c)=>cleaned=c},document:{addEventListener:(event,fn)=>listeners[event]=fn},window:{fetch:async(...args)=>{calls.push(args);return {};}}};vm.runInNewContext(bootstrap('synthetic-token').replace(/^<script>|<\/script>$/g,''),context);await context.window.fetch('/practice/turn',{});await context.window.fetch('https://api.openai.com/v1/realtime/calls',{});await context.window.fetch('/admin',{});assert.equal(calls[0][1].headers.get('authorization'),'Bearer synthetic-token');assert.equal(calls[1][1].headers,undefined);assert.equal(calls[2][1].headers,undefined);assert.equal(cleaned,'/practice?embed=1');});
